name: CI Pipeline with Security Scans

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-security:
    runs-on: ubuntu-latest
    steps:
      # Проверяем код из репозитория
      - uses: actions/checkout@v3

      # Клонируем Juice Shop
      - name: Clone Juice Shop
        run: |
          git clone https://github.com/juice-shop/juice-shop.git

      # Отладка: Проверяем содержимое директории juice-shop
      - name: Debug Juice Shop contents
        run: |
          ls -la juice-shop
          cat juice-shop/package.json || echo "package.json not found"

      # Настраиваем Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Устанавливаем зависимости Juice Shop
      - name: Install Juice Shop dependencies
        run: |
          cd juice-shop
          npm install

      # SAST: Запускаем Semgrep
      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/ci
          publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}

      # Запускаем Juice Shop для DAST
      - name: Start Juice Shop
        run: |
          cd juice-shop
          npm start &
          sleep 10

      # DAST: Запускаем OWASP ZAP
      - name: Run OWASP ZAP
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'http://localhost:3000'
          fail_action: true
