name: CI Pipeline with Security Scans

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-security:
    runs-on: ubuntu-latest
    steps:
      # Проверяем код из репозитория
      - uses: actions/checkout@v3

      # Клонируем Juice Shop
      - name: Clone Juice Shop
        run: |
          git clone https://github.com/juice-shop/juice-shop.git

      # Отладка: Проверяем содержимое директории juice-shop
      - name: Debug Juice Shop contents
        run: |
          ls -la juice-shop
          cat juice-shop/package.json || echo "package.json not found"

      # Настраиваем Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Устанавливаем зависимости Juice Shop
      - name: Install Juice Shop dependencies
        run: |
          cd juice-shop
          npm install --legacy-peer-deps

      # Проверяем уязвимости с помощью npm audit
      - name: Run npm audit
        run: |
          cd juice-shop
          npm audit || echo "npm audit completed with issues"

      # SAST: Запускаем Semgrep
      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/ci
          publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}

      # Запускаем Juice Shop для DAST
      - name: Start Juice Shop
        run: |
          cd juice-shop
          npm start &
          sleep 10

      # DAST: Запускаем OWASP ZAP с конкретным тегом
      - name: Run OWASP ZAP
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'http://localhost:3000'
          fail_action: true
          docker_name: 'owasp/zap2docker-stable'  # Используем образ из GHCR с конкретным тегом

      # Отладка: Показываем npm логи при ошибке
      - name: Show npm logs
        if: failure()
        run: cat /home/runner/.npm/_logs/*.log
